routes/web.php
<?php

use App\Products;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $datos["products"]=Products::paginate(5);
    return view('home',$datos);
});

Auth::routes();

Route::resource('categories', 'CategoriesController');
Route::resource('products', 'ProductsController');

Route::get('/home', 'HomeController@index')->name('home');

app/Products.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Products extends Model
{
    //
    protected $table = 'products';
 
    //Definimos los campos que se pueden llenar con asignación masiva
    protected $fillable = ['name', 'description','photo','price','currency','category_id'];
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use App\Categories;
use App\Http\Requests\ValidateProducts;
use App\Products;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use FFI\Exception;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use App\Logs;
use PDOException;
use RealRashid\SweetAlert\Facades\Alert;

class ProductsController extends Controller
{
    public $table = "products";

    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $datos[$this->table] = Products::paginate(5);
        return view($this->table . '.index', $datos);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $datos["categories"] = Categories::all();
        return view($this->table . '.create', $datos);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ValidateProducts $request)
    {
        //
        $message = '';
        $product = $request->validated();
        try {
            if ($request->file('photo')) {
                $product['photo'] = $request->file('photo')->store('public/uploads');
                $product['photo'] = str_replace("public/uploads", "uploads", $product['photo']);
            }
            Products::create($product);
            $message = 'Producto ' . $product['name'] . ' agregado correctamente';
            Alert::toast($message, 'success');
            return redirect($this->table);
        } catch (PDOException $ex) {
            $message = 'Hubo un error al modificar el producto ' . $product['name'];
            Log::error('Error', ['data' => $product, 'error' => $ex]);
            Alert::toast($message, 'error');
            return redirect($this->table . '/create')->with(['product' => $product])->withErrors(['missingFields' => 'Ocurrio un error ']);
        } catch (Exception $ex) {
            Log::error('Error', ['data' => $product, 'error' => $ex]);
            $message = 'Hubo un error al crear ' . $product['name'];
            Alert::toast($message, 'error');
            return redirect($this->table . '/create');
        } finally {
            $this->logProducts($message);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Products  $products
     * @return \Illuminate\Http\Response
     */
    public function show(Products $products)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Products  $products
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $product = Products::findOrFail($id);
        $datos["categories"] = Categories::all();
        return view($this->table . '.edit', $datos, compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Products  $products
     * @return \Illuminate\Http\Response
     */
    public function update(ValidateProducts $request, $id)
    {
        //
        $message = '';
        $product = $request->validated();
        try {
            if ($request->file('photo')) {
                $oldProduct = products::findOrFail($id);
                Storage::delete('public/' . $oldProduct->photo);
                $product['photo'] = $request->file('photo')->store('public/uploads');
                $product['photo'] = str_replace("public/uploads", "uploads", $product['photo']);
            }
            $message = 'Producto ' . $product['name'] . ' modificado con éxito ';
            Products::where('id', '=', $id)->update($product);
            Alert::toast($message, 'success');
            return redirect($this->table);
        } catch (PDOException $ex) {
            $message = 'Hubo un error al modificar el producto ' . $product['name'];
            Log::error('Error', ['data' => $product, 'error' => $ex]);
            Alert::toast($message, 'error');
            return redirect($this->table  . '/' . $id . '/edit')->with(['product' => $product])->withErrors(['missingFields' => 'Ocurrio un error ']);
        } catch (Exception $ex) {
            $message = 'Hubo un error al modificar el producto ' . $product['name'];
            Log::error('Error', ['data' => $product, 'error' => $ex]);
            Alert::toast($message, 'error');
            return redirect($this->table  . '/' . $id . '/edit')->with(['product' => $product])->withErrors(['Error' => 'Ocurrio un error ']);
        } finally {
            $this->logProducts($message);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Products  $products
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Products::findOrFail($id);
        $message = '';
        try {
            Products::destroy($id);
            if (Storage::delete('public/' . $product->photo)) {
                products::destroy($id);
            }
            $message = 'Producto ' . $product->name . ' eliminada con éxito ';
            Alert::toast($message, 'success');
            return redirect($this->table);
        } catch (Exception $ex) {
            $message = 'Hubo un error al eliminar el producto ' . $product->name;
            Log::error('Error', ['data' => $product, 'error' => $ex]);
            Alert::toast($message, 'error');
            return redirect($this->table);
        } finally {
            $this->logProducts($message);
        }
    }

    public function logProducts($description)
    {
        try {

            $log = [
                'user' => Auth::user()['email'],
                'source' => $this->table,
                'type' => 'Audit',
                'ipAddress' =>  $_SERVER['HTTP_CLIENT_IP'] ?? '1270.0.1',
                'userAgent' => $_SERVER['HTTP_USER_AGENT'] ?? '',
                'description' => $description,
            ];
            Logs::create($log);
        } catch (Exception $ex) {
        }
    }
}

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Crear un producto</div>
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <form action="{{url('/products')}}" method="post" enctype="multipart/form-data">
                        {{csrf_field()}}
                        @include('products.form', ['type'=>'create'])
                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Editar un producto</div>
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    
                    <form action="{{url('/products/'.$product->id)}}" method="post" enctype="multipart/form-data">
                        {{csrf_field()}}
                        {{method_field('PATCH')}}
                        @include('products.form', ['type'=>'editar'])
        
                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/products/form.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
    <div>

        <div>
            <div class="form-group row">
                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Nombre') }}</label>

                <div class="col-md-6">
                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name"
                    value="{{$product->name ?? ''}}" required autocomplete="name" autofocus>

                    @error('name')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
            </div>

            <div class="form-group row">
                <label for="description" class="col-md-4 col-form-label text-md-right">{{ __('Descripción') }}</label>

                <div class="col-md-6">
                    <input id="description" type="text" class="form-control @error('description') is-invalid @enderror"
                        name="description" value="{{$product->description ?? ''}}" required autocomplete="description" autofocus>

                    @error('description')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
            </div>
            <div class="form-group row">
                    <label for="mobile" class="col-md-4 col-form-label text-md-right">{{ __('Precio') }}</label>
    
                    <div class="col-md-6">
                        <input id="price" type="float" class="form-control @error('price') is-invalid @enderror"
                            name="price" value="{{$product->price ?? ''}}" required autocomplete="price" autofocus>
    
                        @error('price')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
            </div>
            <div class="form-group row">
                    <label for="currency" class="col-md-4 col-form-label text-md-right">{{ __('Moneda') }}</label>
    
                    <div class="col-md-6">
                            <select value="" name="currency" id="currency" class="form-control @error('currency') is-invalid @enderror" required autocomplete="currency" autofocus>
                                    <option value="">-- Selecciona una opción --</option>    
                                    <option {{$product->currency ?? '' =='COP' ? ' selected ':''}} value="COP">Peso Colombiano</option>
                                    <option {{$product->currency ?? ''=='USD' ? ' selected ':''}} value="USD">Dolar Estadounidense</option>
                            </select>
                        @error('currency')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
            </div>
            <div class="form-group row">
                    <label for="category" class="col-md-4 col-form-label text-md-right">{{ __('Categoria') }}</label>
                    <div class="col-md-6">
                            <select value="{{$product->category ?? ''}}" name="category_id" id="category" class="form-control @error('category_id') is-invalid @enderror"  required autocomplete="category_id" autofocus>
                                    <option value="">-- Selecciona una opción --</option>
                                    @foreach ($categories as $category)
                                        <option {{ $product->category_id ?? ''== $category->id ? ' selected ':''}} value="{{ $category->id }}">{{ $category->name }}</option>
                                    @endforeach
                            </select>
                        @error('category_id')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
            </div>
            <div class="form-group row">
                    <label for="photo" class="col-md-4 col-form-label text-md-right">{{ __('Foto') }}</label>

                    <div class="col-md-6">
                        @if(isset($product->photo))
                        <img src="{{ asset('storage').'/'.$product->photo}}" alt="" width="100">
                        @endif

                        <input id="photo" type="file" class="form-control @error('photo') is-invalid @enderror"
                            name="photo" accept="image/png, image/jpeg" value="{{$product->photo ?? ''}}" 
                            autocomplete="photo" autofocus>

                        @error('photo')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                </div>

            <div class="form-group row mb-0">
                <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                        {{$type=='create'? 'Agregar': 'Modificar'}}
                    </button>
                </div>
            </div>
        </div>

    </div>
</body>

</html>

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <div class="row justify-content-left">
                        <div class="col-sm-8">
                            <h1>Productos</h1>
                        </div>
                        <div class="col-sm-4">
                            <a class="btn btn-primary" href="{{route('products.create')}}">Agregar un producto</a>
                        </div>
                    </div>
                </div>

                <div class="card-body">
                    @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                    @endif
                    <table class="table table-striped">
                        <thead class="thead">
                            <tr>
                                <th>Foto</th>
                                <th>Nombre</th>
                                <th>Descripción</th>
                                <th>Precio</th>
                                <th>Moneda</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if(count($products)>0)
                            @foreach($products as $product)
                            <tr>
                                <td>
                                    @if($product->photo)
                                    <img src="{{ asset('storage').'/'.$product->photo}}" alt="" width="100">
                                    @else
                                    <img  src="{{asset('img/no-image-icon.png')}}"  alt="" width="100">
                                    @endif

                                </td>
                                <td>{{$product->name}}</td>
                                <td>{{$product->description}}</td>
                                <td>{{number_format($product->price, 2)}}</td>
                                <td>{{$product->currency}}</td>
                                <td>
                                    <div class="form-group row">
                                        <a href="{{url('products/'.$product->id.'/edit')}}"
                                            class="btn btn-secondary m-2">Editar</a>

                                        <form method="post" action="{{url('products/'.$product->id)}}">

                                            {{csrf_field()}}
                                            {{method_field('DELETE')}}
                                            <button class="btn btn-primary m-2" type="submit"
                                                onclick="return confirm('Desea borrar el producto {{$product->name}}');">Borrar</button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                            @else
                            <tr>
                                <td colspan="6">No se han encontrado registros</td>
                            </tr>
                            @endif
                        </tbody>
                    </table>
                    
                    <div class="form-group row  justify-content-center">
                        {!!$products->render()!!}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection